Not work question edit
filinivan/TestGuru pull request #10
Opened 2021-05-20 13:15 UTC by filinivan

Не могу понять почему edit (http://localhost:3000/tests/1/questions) отображает ссылку на один и тот же вопрос у разных. Вижу, что она берёт ссылку из id теста, но как исправить ситуацию понять не могу.. Need help.

2021-05-20 13:18 UTC, filinivan commented
Прошу прощения, что в этот пул реквест свалил столько изменений. Вернулся к обучению спустя 4 месяца паузы..

2021-05-20 19:27 UTC, BubuntuClu requested changes

2021-05-20 19:27 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.new
инициализировать стоит через ассоциацию тоже

2021-05-20 19:27 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>    def test_questions
это и ниже метод, они для чего? их стоит удалить, они не нужны

2021-05-20 19:27 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +      @test = Test.find(params[:id])
этот код дублируется. стоит вынесит в метод/колбэк

2021-05-20 19:27 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +        @tests = Test.all
отступы прыгают. надо чтобы был один отступ у всех методов

2021-05-20 19:27 UTC, BubuntuClu commented on app/helpers/tests_helper.rb
> +  def question_header(test)
почему заголовок для вопроса, а передаем тест? надо передавать сюда вопрос. и если тут заголовок для вопроса, то стоит поместь в хэлпер вопросов

2021-05-20 19:27 UTC, BubuntuClu commented on app/helpers/tests_helper.rb
> +  def current_year
этот метод и метод ниже не относятся к тестам. это общие хэлперы приложения. стоит поместить в application_helper

2021-05-20 19:27 UTC, BubuntuClu commented on app/helpers/tests_helper.rb
> +    link = link_to author, repo
`link =` лишнее

2021-05-20 19:31 UTC, BubuntuClu commented
>Не могу понять почему edit (http://localhost:3000/tests/1/questions) отображает ссылку на один и тот же вопрос у разных.

ссылка для редактирования вопроса? если да, то она неправильная. у тебя используется опция `shallow: true`, путь до редактирования вопроса будет другой. посмотри `rake routes`.

даже если такой путь, то нужен id для вопроса. у тебя отрабатывают два колбэка для метода edit - нахождение вопроса и нахождение теста(хотя зачем тебе тест в редактировании вопроса?). в роуте у тебя получается test_id =1, а id вопроса нет. из-за этого должно отрабатывать событие что вопрос не найден

может я неправильно вопрос понял? но при твоем текущем коде это не будет работать.

1- надо использовать правильный путь
2- поправить колбэки в контроллере вопросов
3- для дебага можно поставить гем `pry` или `byebug` и посмотреть как у тебя происходит отрабатывание методов

2021-05-21 09:28 UTC, filinivan commented on app/helpers/tests_helper.rb
> +  def question_header(test)
В задании сказано : Для заголовка формы создания и редактирования вопроса. Это должен быть один метод question_header который в форме создания вопроса будет выводить Create New <Test Title> Question, а в форме редактирования Edit <Test Title> Question. Я понял, что нужно отобразить название теста для которого создаётся или редактируется вопрос.

2021-05-21 12:45 UTC, BubuntuClu commented on app/helpers/tests_helper.rb
> +  def question_header(test)
да, все правильно. только передавать для этого достаточно только вопрос. остальное мы все можем из него получить. проверяем внутри метода существует ли вопрос

2021-05-21 12:52 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> -  before_action :find_test, only: %i[create new]
есть конечно споры между колбэками/вызовом методов в экшенах напрямую. мне кажется, что установка значения допустима через колбэки

2021-05-21 12:52 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    redirect_to @test
откуда тут береться `@test`? ты удалил колбэки

2021-05-21 12:52 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +    if question.persisted?
переменная text и return не нужны в этом методе. в рубях return автоматически выполняется для последней исполненной команды

2021-05-23 20:44 UTC, merged