10 authentity
filinivan/TestGuru pull request #12
Opened 2021-07-07 13:28 UTC by filinivan

2021-07-07 21:20 UTC, filinivan commented on .ruby-version
> -ruby-2.7.0
Прошу прощения за такие манёвры - настроил на домашнем компьютере wsl на windows 10. Что бы была возможность вечером сидеть ... Часть файлов проекта переписалось)

2021-07-08 18:22 UTC, BubuntuClu requested changes

2021-07-08 18:22 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:action] = params["action"]
сохрани просто путь из `request`, там много вариантов где он может лежать. вроде один из вариантов `request.fullpath`

2021-07-08 18:22 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      redirect_to :controller=>cookies[:controller], :action=>cookies[:action]
тут будет `redirect_to cookies[:requested_url] || root_path`
когда сохранишь путь более лаконичным способом

2021-07-08 18:22 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:action] = params["action"]
там ведь еще могут быть параметры в url, твоим способом ты их не сохраняешь

2021-07-08 18:22 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +  before_action :authenticate_user!
выглядит так, как будто можно поместить этот метод в `ApplicationController` вместо того чтобы прописывать его в каждом дочернем

2021-07-08 18:22 UTC, BubuntuClu commented on config/routes.rb
> +  get :signup, to: 'users#new'
дубль строки 4

2021-07-08 18:22 UTC, BubuntuClu commented on db/migrate/20210707123541_add_index_to_users.rb
> +    add_index :users, :email, unique: true
зачем отдельная миграция на создания индекса? сделай все за раз в миграции `ChangeUsers`

2021-07-08 18:22 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, presence: true
в БД ты добавил индекс уникальности, хорошо еще в модель ее добавить

2021-07-08 18:22 UTC, BubuntuClu commented on db/migrate/20210610125640_add_password_digest_to_users.rb
> +class AddPasswordDigestToUsers < ActiveRecord::Migration[6.0]
почему на каждое изменение в таблице ты делаешь отдельную миграцию? все изменения касаются одной таблицы, можно их объединить

2021-07-08 18:22 UTC, BubuntuClu commented on db/migrate/20210611110758_change_users.rb
> +      t.rename :username, :email # t.string -> t.rename
а имен теперь не будет у пользователей? можно было бы рядом добавить просто колонку рядом с этой, не помешала бы

2021-07-08 18:22 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +
`safe_join(flash.map { |key, msg| content_tag :p, msg, class: "flash #{key}" })`

типов сообщений может быть несколько, не только алерт

2021-07-09 09:59 UTC, filinivan commented on app/controllers/sessions_controller.rb
> +      redirect_to :controller=>cookies[:controller], :action=>cookies[:action]
Как круто !

2021-07-09 10:02 UTC, filinivan commented on db/migrate/20210707123541_add_index_to_users.rb
> +    add_index :users, :email, unique: true
База данных уже существовала на тот момент. Решил не менять уже отработанные миграции, а накатить новой. Как будто "боевой" проект) Поправить в прошлых миграциях конечно проще.

2021-07-09 10:02 UTC, filinivan commented on db/migrate/20210610125640_add_password_digest_to_users.rb
> +class AddPasswordDigestToUsers < ActiveRecord::Migration[6.0]
Просто они делались в разное время.

2021-07-09 17:45 UTC, BubuntuClu commented on db/migrate/20210707123541_add_index_to_users.rb
> +    add_index :users, :email, unique: true
так и нельзя делать, править старые миграции. я про миграцию ChangeUsers которая этом ПРе

2021-07-09 17:47 UTC, BubuntuClu commented on db/migrate/20210610125640_add_password_digest_to_users.rb
> +class AddPasswordDigestToUsers < ActiveRecord::Migration[6.0]
а что это меняет? ПР то в итоге выглядит грязным) ты же можешь откатить миграции и поправить, чтобы все делалось в одной новой миграции. сейчас у тебя 3

2021-07-09 20:19 UTC, merged