Without last task
filinivan/TestGuru pull request #13
Opened 2021-07-21 13:54 UTC by filinivan

2021-07-21 19:07 UTC, BubuntuClu requested changes

2021-07-21 19:07 UTC, BubuntuClu commented on app/controllers/admin/answers_controller.rb
> +class Admin::AnswersController < ApplicationController
другой контроллер родительский будет использоваться

2021-07-21 19:07 UTC, BubuntuClu commented on app/controllers/admin/base_controller.rb
> +    redirect_to root_path, alert: 'You are not admin' unless current_user.is_a?(Admin)
добавь метод в модель `User` который будет проверять является ли пользователь админом. `admin?`

2021-07-21 19:07 UTC, BubuntuClu commented on app/controllers/admin/questions_controller.rb
> +class Admin::QuestionsController < ApplicationController
и тут. для всех админский контроллеров

2021-07-21 19:07 UTC, BubuntuClu commented on app/controllers/admin/questions_controller.rb
> +      redirect_to [:admin, @test]
мне больше нравится использовать url хэлперы, который показывает `rake_routes` типа admin_tests_path

2021-07-21 19:07 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +    def start
старт в админке не нужен

2021-07-21 19:07 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +      @test = Test.new(test_params)
используй ассоциацию созданных тестов у пользователя вместо костыля ниже

2021-07-21 19:07 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    if current_user.is_a?(Admin)
`resource.admin?`

2021-07-22 21:26 UTC, filinivan commented on app/controllers/admin/questions_controller.rb
> +      redirect_to [:admin, @test]
А в подобном ключе не получится использовать URL хелпер?
def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to [:admin, @answer.question]
    else
      render :new
    end
  end

2021-07-22 21:39 UTC, filinivan commented on app/controllers/admin/tests_controller.rb
> +      @test = Test.new(test_params)
Пока не могу понять как ещё это можно реализовать. Если можно - небольшую подсказку...

2021-07-23 14:01 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +      @test = current_user.created_tests.new(test_params)
во, шикардос

2021-07-23 14:01 UTC, BubuntuClu commented on app/models/user.rb
> +    if self.type == 'Admin'
`type == 'Admin'` это и так тебе вернет `true/false`, руками не надо расписывать

```
def admin?
  type == 'Admin'
end
```

2021-07-23 14:01 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +      params.require(:test).permit(:title, :level, :category_id, :creator)
`:creator` а это что за покемон? тебе это тут не нужно, ты через `current_user` создаешь тест

2021-07-26 07:17 UTC, merged