Lesson  7 controller
filinivan/TestGuru pull request #9
Opened 2021-01-13 13:34 UTC by filinivan

2021-01-13 16:44 UTC, BubuntuClu requested changes

2021-01-13 16:44 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def test_question
этот метод для чего используется?

2021-01-13 16:44 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def create
Параметры с фронта могут быть не валидные, это надо учитывать
```
question = @test.questions.new(questions_params)
if question.save
  Render good
else
  Render bad
end
```

2021-01-13 16:44 UTC, BubuntuClu commented on config/routes.rb
> +  resources :questions
отдельно ресурс вопросов не нужен

2021-01-13 16:44 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions
добавь опцию `shallow: true` для вопросов

2021-01-13 16:44 UTC, BubuntuClu commented on public/new_question.html.erb
> +<!DOCTYPE html>
это должна быть не публичная страница, а вьюха для твоего метода контроллера

2021-01-13 16:44 UTC, BubuntuClu commented on public/new_question.html.erb
> +            <p><%= f.label :test_id %>
это надо брать из параметра в юрл, а не выбирать руками

2021-01-14 11:33 UTC, BubuntuClu requested changes

2021-01-14 11:33 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def test_question
зачем нужен этот метод?(2)

2021-01-14 11:33 UTC, BubuntuClu commented on public/new_question.html.erb
> +<!DOCTYPE html>
это надо удалить

2021-01-14 11:47 UTC, filinivan commented on app/controllers/questions_controller.rb
> +  def test_question
Этот метод уже удалён. Из-за того, что несколько пулл реквестов вы не увидели.

2021-01-14 12:17 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def test_question
странно. вижу только один ПР и если открыть измененные файлы, то он есть. может не запушил?

2021-01-14 19:56 UTC, merged